### PR TITLE
add LotV-related tests

### PR DESCRIPTION
**Pull request by dsjoerg**
Hi @StoicLoofah I added two tests, one for simple replay parsing which passes, and another for map parsing which currently fails.

I'll look at the map parsing and see if I can figure out what's going on... if not then hopefully the big guns like @GraylinKim can figure it out

### CODE REVIEW

**Comment by StoicLoofah** [comment]
Looks good to me; thanks for being more diligent than myself. Would you prefer that I merge it in now, or would you rather I wait for the map parsing fix?

**Comment by dsjoerg** [comment]
I say merge it now; then anyone who wants to work on the map parsing fix can do it right on the branch.

**Comment by dsjoerg** [comment]
Now this PR is even better (hopefully you agree) with the addition of a full set of LotV abilities and units thanks to @mischanix.
You'll note that replay parsing in the unit test no longer complains about missing unit types and abilities (with one weird exception, ability 1326).

**Comment by robert-nix** [comment]
Some notes on the dump script change (feel free to amend the commit with these):
- Reformatted to normalize whitespace to tabs
- Reorganized to avoid declarations and some verbosity
- Dropped support for 32-bit and with it support for old builds in favor of 64-bit
- Updated all offsets for the 64-bit build of 37164

Ping me when there's another build of LotV and I'll update it and try to rewrite the instructions for future updates; until then, I'm not going to make a guess at what offsets change from build-to-build.

**Comment by StoicLoofah** [comment]
Sweet. Thanks for the new data dump.

**Pull request merged**
